### PR TITLE
DOCUMENATATION FIX

### PR DESCRIPTION
**Pull request by code-reaper08**
## Changes done 

1. Typos and formatting errors fixed in [README.md](https://github.com/mamamia5x/markdownpedia/blob/main/README.md)

2. Updated [README.md](https://github.com/code-reaper08/markdownpedia/blob/main/README.md) with [**useful resources**](https://github.com/code-reaper08/markdownpedia#useful-resources) section for First-time contributors.

3. Included a [LICENSE.md](https://github.com/code-reaper08/markdownpedia/blob/main/LICENSE.md) file which clearly describes the license with which [Markdownpedia](https://github.com/mamamia5x/markdownpedia) works.

4. Included a general [CODEOFCONDUCT.md](https://github.com/code-reaper08/markdownpedia/blob/main/CODEOFCONUCT.md) adapted from [Contributor Covenant](https://www.contributor-covenant.org/).

5. Included a [CONTRIBUTING.md](https://github.com/code-reaper08/markdownpedia/blob/main/CONTRIBUTING.md), which clearly gives the guidelines for contributing to markdownpedia.

### CODE REVIEW

**Comment by mamamia5x** [comment]
Holy cow this is really good, thanks for helping me.

**Comment by code-reaper08** [comment]
> Holy cow this is really good, thanks for helping me.

Thanks for your appreciation 😁
It really motivates me ✔✨🙏

**Comment by mamamia5x** [comment]
No problem, but really thanks a lot for helping. If you go the site, you'll see that you are now added as an editor.

**Comment by code-reaper08** [comment]
> No problem, but really thanks a lot for helping. If you go the site, you'll see that you are now added as an editor.

Hey  @mamamia5x ✨No problem 
Thanks for adding me as a editor.
let me know if you need any help ❤

Thanks again 🙏🎉

**Comment by mamamia5x** [comment]
No problem, thanks for helping out.

**Pull request merged**
