### PR TITLE
Allow the user to use the editor and have their markdown files saved.

### PR DESCRIPTION
**Pull request by fleventy-5**
Can allow  the user to use the editor and have their markdown files saved.
also included file open capabilities

### CODE REVIEW

**Comment by fleventy-5** [comment]
@mamamia5x  do tell me if you want to add any changes .
Thanks

**Comment by fleventy-5** [comment]
This is the output of the editor

**Review by mamamia5x — APPROVED** [review]
Wow, really good job. Saved me a bunch of time.

**Comment by fleventy-5** [comment]
Hey @mamamia5x  thanks for merging my pull request do let me know if you need any help

**Comment by mamamia5x** [comment]
No problem @fleventy-5
Thank you so much, it saves me so much time when someone can help me.
You are added to the Contributors section on the site https://markdownpedia.tk/

**Pull request merged**
